### ISSUE TITLE
Reintegrate Arduino_ConnectionHandler with ArduinoIoTCloud

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/ArduinoIoTCloud#106]
Initially a part of ArduinoIoTCloud the [Arduino_ConnectionHandler](https://github.com/arduino-libraries/Arduino_ConnectionHandler) has been extracted into a separate library. Unfortunately this has turned out to be a bad decision because the constant changes to both `ArduinoIoTCloud` and `Arduino_ConnectionHandler` require regular modifications to both which either need to be released simultaneously or require an intricate update strategy. Since this has happened multiple times in the past it has become clear that `Arduino_ConnectionHandler` should be reintegrated with `ArduinoIoTCloud`.

**Comment by aentinger** [comment]
@ubidefeo What's your opinion on this?

**Comment by ubidefeo** [comment]
@aentinger I'm not in favour of integrating it back.
How about integrating a fork?
The ConnectionHandler is very useful in a lot of situations outside of the IoT Cloud contexts

**Comment by per1234** [comment]
I don't know what the "intricate update strategy" situation is about, but regarding "need to be released simultaneously", you could add Arduino_ConnectionHandler as a [git subtree](https://www.atlassian.com/git/tutorials/git-subtree) of this repository. That allows keeping the Arduino_ConnectionHandler as a separate library while also avoiding the possibility of incompatible versions of the two libraries being used together.

**Comment by aentinger** [comment]
@ubidefeo Actutally I'm seriously doubting that there is a substantial (> 5) user base which uses `Arduino_ConnectionHandler` as a stand-alone library (not in combination with `ArduinoIoTCloud`). Unfortunately I can't prove this and I would not know from where to get those numbers since in this case this argument would be solved in a heartbeat.

@per1234 [git-subtree](https://www.atlassian.com/git/tutorials/git-subtree) might be an idea, I'll have to take a closer look myself.

**Comment by aentinger** [comment]
After seriously cleaning up `Arduino_ConnectionHandler` I've become convinced that right now there is no need to integrate it with `ArduinoIoTCloud`.
