### ISSUE TITLE
ArduinoCloud doesn't automatically reconnect?

### ISSUE THREAD

**Issue by jcham** [arduino-libraries/ArduinoIoTCloud#220]
The simple example projects to light up an LED work fine, but the whole thing stops working when WiFi connection gets momentarily lost, and it doesn't reconnect, requiring a reset.
If this is normal, then what is the recommended way to detect a disconnect and reconnect?
Thanks

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino-libraries/ArduinoIoTCloud/issues/221
