### ISSUE TITLE
using ArduinoBearSSL as a library

### ISSUE THREAD

**Issue by gannaramu** [arduino-libraries/ArduinoIoTCloud#285]
I see that there is a port of bearssl in the tls folder. is there a reason for not using the ArduinoBearSSL library instead?

**Comment by aentinger** [comment]
Yes. This allows us to define a narrow profile (defining the supported encryption algorithms) therefore preserving much needed space. See [aiotc_profile.c](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/master/src/tls/profile/aiotc_profile.c).

**Comment by gannaramu** [comment]
The reason for that query was the ArduinoBearSSL nor the ArduinoECCX08 do not include a few files such as the CryptoUtil and the ECCX08Cert. Are there any plans of including them in ArduinoBearSSL? @aentinger

**Comment by aentinger** [comment]
>Are there any plans of including them in ArduinoBearSSL?

No.
