### ISSUE TITLE
Callback Sync only works once after reboot

### ISSUE THREAD

**Issue by Frodo1980** [arduino-libraries/ArduinoIoTCloud#295]
Sync-Callback works fine but only once after reboot of device. Is it because of ESP32-board? Thing is connected and values are uploaded to IoT-Cloud, but the Sync-Event does not call the function again.

**Comment by aentinger** [comment]
Hi @Frodo1980 :wave: Can you please share a minimal example exhibiting the problematic behaviour?

**Comment by pennam** [comment]
@aentinger @Frodo1980 looking at the code i think this is the intended behaviour. 
The `onSync` callback is triggered only when the board properties are synched to cloud properties and this is done once each time the board starts. After the sync event the `onChange` callback is triggered when the propertiy value is updated.
