### ISSUE TITLE
Remove `#if !defined(__AVR__)` to improve code clarity.

### ISSUE THREAD

**Issue by aentinger** [arduino-libraries/ArduinoIoTCloud#299]
All those
```C++
#if !defined(__AVR__)
    /* ... */
#endif
```
statements can be safely removed (of course preserving the statements within those ifdef/endif parts), i.e.
```diff
-#if !defined(__AVR__)
  DEBUG_ERROR("Check your thing configuration, and press the reset button on your board.");
-#endif
```
Reason: Those statements where introduced to save flash when running Arduino IoT Cloud on the very ressource constrained Arduino Uno WiFi Rev. 2, however the idea of running the cloud stack on this board has long since been given up (and is now more impossible than ever before, due to continous growth of the firmware stack).

**Comment by pennam** [comment]
fixed by https://github.com/arduino-libraries/ArduinoIoTCloud/pull/311
