### ISSUE TITLE
Feature Request: Ethernet Example for Portenta with Ethernet Vision Shield

### ISSUE THREAD

**Issue by hpssjellis** [arduino-libraries/ArduinoIoTCloud#305]
@pennam 

Feature Request: Ethernet Example for Portenta with Ethernet Vision Shield

I can test out anyone's code, I might be able to make a stab at this.

Looking at   [Arduino_ConnectionHandler.h](https://github.com/arduino-libraries/Arduino_ConnectionHandler/blob/master/src/Arduino_ConnectionHandler.h) I don't think Ethernet has been included.

**Comment by per1234** [comment]
It looks like the support for Ethernet on Portenta H7 is in progress, but no example as of yet: https://github.com/arduino-libraries/ArduinoIoTCloud/pull/328

**Comment by pennam** [comment]
Hi @hpssjellis,
the support for ethernet on Portenta H7 is done now. Please let me know if you need more details on this.

**Comment by hpssjellis** [comment]
All good thanks @pennam
