### ISSUE TITLE
SE050 support library

### ISSUE THREAD

**Issue by zorc1985** [arduino-libraries/ArduinoIoTCloud#336]
Where is the file [`SE05X.h`](https://github.com/arduino-libraries/ArduinoIoTCloud/blob/master/src/tls/utility/CryptoUtil.h#L32)? Am I right that this is a placeholder for a library that is yet to be created? How do I use the SE050 on the Portenta H7?

**Comment by pennam** [comment]
Portenta H7 do not use `SE050` to connect to ArduinoIoTCloud, it uses `ECC608`.
SE050X.h file is here https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/SE05X/src/SE05X.h
`SE050` support is not enabled in the core for Portenta H7 but only for Nicla Vision.

**Comment by zorc1985** [comment]
Thnks for the link to ArduinoCore-mbed.

As for the Portenta H7, [this here](https://store-usa.arduino.cc/products/portenta-h7?selectedStore=us) says SE050. I haven't bought it yet but it seems between ArduinoIoTCloud and ArduinoCore-mbed I have everything I will need to tap into its SE050.
