### ISSUE TITLE
Version 1.10.0 - Error in OTA.h

### ISSUE THREAD

**Issue by mhavill** [arduino-libraries/ArduinoIoTCloud#357]
I have raised this in https://community.platformio.org/t/arduinoiotcloud-update-error/32899 as I use PlatformIO as my IDE, but I think it belongs here?

Board - ESP32-Wrover Devkitc

Experienced the problem in my own project but I can reproduce in the AtduinoIoTCloud-Basic sketch also.  On building I get 
`.pio/libdeps/az-delivery-devkit-v4/ArduinoIoTCloud/src/utility/ota/OTA.h:65:36: error: ‘NetworkAdapter’ has not been declared`

Reverting to 1.9.0 builds without error

**Comment by per1234** [comment]
Hi @mhavill. Thanks for your report. Which version of the [**Arduino_ConnectionHandler**](https://registry.platformio.org/libraries/arduino-libraries/Arduino_ConnectionHandler) library dependency are you using?

**Comment by mhavill** [comment]
Dependency graph shows Arduino_ConnectionHandler @ 0.6.6


```
|-- ArduinoIoTCloud @ 1.11.0
| |-- Arduino_ConnectionHandler @ 0.6.6
| | |-- WiFi @ 2.0.0
| | |-- Arduino_DebugUtils @ 1.4.0
| |-- WiFi @ 2.0.0
| |-- Arduino_DebugUtils @ 1.4.0
| |-- WiFiClientSecure @ 2.0.0
| | |-- WiFi @ 2.0.0
| |-- ArduinoMqttClient @ 0.1.7
|-- Arduino_ConnectionHandler @ 0.6.6
| |-- WiFi @ 2.0.0
| |-- Arduino_DebugUtils @ 1.4.0
```

**Comment by per1234** [comment]
OK, that is the problem. You are using an outdated version of the **Arduino_ConnectionHandler** library depdendency from before this change:

https://github.com/arduino-libraries/Arduino_ConnectionHandler/commit/37758d37af1b21ef8c54e3041dc039b1dba13cf8

Please update to the latest version of the **Arduino_ConnectionHandler** library depdendency

**Comment by mhavill** [comment]
Thank you for your rapid response and help!
