### ISSUE TITLE
Compilation of my sketch fails: "`'class ArduinoIoTCloudTCP' has no member named 'getFloatProperty'`"

### ISSUE THREAD

**Issue by msmuringo** [arduino-libraries/ArduinoIoTCloud#358]
Anyone who can assist on which Library uses the class : `ArduinoIoTCloudTCP`. I am using the `ArduinoIoTCloudTCP` library but getting an the error below, indicating that the library does not have the member functions:-

```text
/tmp/972368038/Untitled_apr01a/Untitled_apr01a.ino:119:31: error: 'class ArduinoIoTCloudTCP' has no member named 'getFloatProperty'

^

Error during build: exit status 1
```

**Comment by per1234** [comment]
Hi @msmuringo. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/software/iot-cloud/152
