### ISSUE TITLE
Include the capability to send messages from the modules to the messenger dashboard 

### ISSUE THREAD

**Issue by delcioDEV** [arduino-libraries/ArduinoIoTCloud#360]

**Comment by pennam** [comment]
@delcioDEV can you please post the link content directly on github?

**Comment by delcioDEV** [comment]
![Captura de ecrã 2023-05-24 153402](https://github.com/arduino-libraries/ArduinoIoTCloud/assets/90966998/d5138f57-21ec-4b61-af59-97fa36efd732)

**Comment by pennam** [comment]
Is possible to send messages from the board to the widget and back from the widget to the board. have you seen this? https://www.youtube.com/watch?v=vEjrJW_pqlo

**Comment by delcioDEV** [comment]
@pennam thkns man preciate that, i colud not find any documentation at all

**Comment by per1234** [comment]
Hi @delcioDEV. Did you see this documentation:

https://docs.arduino.cc/arduino-cloud/getting-started/dashboard-widgets#messenger

If you did see it, do you have any feedback about what was unclear about it?

If you didn't see it, do you think it would have been sufficient to allow you to understand how to accomplish your goal of "send messages from the modules to the messenger dashboard"?

**Comment by delcioDEV** [comment]
@per1234  thanks a lot, no, I hadn't, there is no reference to the documentation nor concrete examples for each widget, it helped a lot, now I can proceed without further ado

**Comment by pennam** [comment]
@delcioDEV i'll close this because it looks like your problem is solved.
