### ISSUE TITLE
ESP32 WROOM 32 DevKit (DIYMall) error connecting to ArduinoCloud

### ISSUE THREAD

**Issue by dvelaren** [arduino-libraries/ArduinoIoTCloud#377]
Hello Arduino community. I would like to report a problem when connecting the ESP32 WROOM 32 DevKit (DIYMall) to ArduinoCloud. I have been following this [tutorial](https://docs.arduino.cc/arduino-cloud/getting-started/esp-32-cloud).

I'm able to connect to upload the program, connect to the WiFi but when the ESP32 tries to connect to the ArduinoCloud MQTT server. It fails with the following errors:

```text
ArduinoIoTCloudTCP::handle_ConnectMqttBroker could not connect to mqtts-up.iot.arduino.cc:8884
ArduinoIoTCloudTCP::handle_ConnectMqttBroker 1 connection attempt at tick time 15112
```

I have tried selecting different boards because I think this is related to client certificates or TLS issues. The boards I tried are:
- DOIT ESP32 DEVKIT V1
- ESP32 Dev Module
- MH ET LIVE ESP32 DevKIT

I hope you can help me out solving this issue.

---

Also reported at https://forum.arduino.cc/t/esp32-wroom-32-devkit-diymall-error-connecting-to-arduinocloud/1165957

**Comment by pennam** [comment]
Let's continue the discussion on the forum.
