### ISSUE TITLE
Negative values 

### ISSUE THREAD

**Issue by daniocarter** [arduino-libraries/ArduinoIoTCloud#382]
Hi I have an issue with negative numbers returning positive after cloud sends variables when the device-thing has been turned on

If you set up 2 cloud variables of type int with read and write set on both, set the values of var1 to 10 and var2 to -10 on the cloud either while the esp8266 is on or off.

When you turn of the esp you would expect the Arduino cloud to connect to it and update the values on the device with the cloud ones (first time OnConnected). Which it does for the positive valued ones but not the negative. The negative values are changed to positive.

Any help please

Thx

**Comment by pennam** [comment]
Hi @daniocarter,
thanks for the head-up, we are working on it. I'll update you as soon as we release a fix.

**Comment by daniocarter** [comment]
Brilliant 👏

**Comment by pennam** [comment]
@daniocarter The issue has been fixed. Can you please retry?

**Comment by daniocarter** [comment]
Yes, it worked.  Thank you

**Comment by pennam** [comment]
Closing as not planned because the issue was not in the library code
