### ISSUE TITLE
Issue with Simultaneous Connections to AWS IoT Core and Arduino Cloud

### ISSUE THREAD

**Issue by djom202** [arduino-libraries/ArduinoIoTCloud#516]
Hi there,

I’m currently using the MQTT library to connect my ESP32 to AWS IoT Core for sending information. However, I’m having trouble keeping the connection open to both AWS IoT Core and Arduino Cloud simultaneously, as the connections seem to overlap at some point.

My question is: Is it possible to maintain both connections at the same time? Are there any strategies or libraries that could help me resolve this issue?

My code: [https://gist.github.com/djom202/d1660f4c9c5b9fa038b753dc6057c7bf](https://gist.github.com/djom202/d1660f4c9c5b9fa038b753dc6057c7bf)

Below are the logs showing the problem:

17:08:37.686 -> [846532][E][NetworkClient.cpp:319] setSocketOption(): fail on 0, errno: 9, "Bad file number"
17:08:37.719 -> [846582][E][NetworkClient.cpp:319] setSocketOption(): fail on 0, errno: 9, "Bad file number"
17:08:37.913 -> [846774][E][ssl_client.cpp:213] start_ssl_client(): useRootCABundle is set, but attach_ssl_certificate_bundle(ssl, true); was not called!
17:08:38.526 -> [847390][E][ssl_client.cpp:36] _handle_error(): [ssl_starttls_handshake():313]: (-30336) SSL - No CA Chain is set, but required to operate
17:08:38.590 -> [847463][E][NetworkClientSecure.cpp:159] connect(): start_ssl_client: connect failed: -30336
17:08:38.654 -> ArduinoIoTCloudTCP::handle_ConnectMqttBroker could not connect to iot.arduino.cc:8884 Error: -2
17:08:38.686 -> [847514][E][NetworkClient.cpp:319] setSocketOption(): fail on 0, errno: 9, "Bad file number"
17:08:38.750 -> [847614][E][NetworkClient.cpp:319] setSocketOption(): fail on 0, errno: 9, "Bad file number"

**Comment by pennam** [comment]
@djom202 i've never tried with an ESP32 but it should be totally feasible. With the opta we use [ArduinoIoTCloud](https://github.com/arduino-libraries/ArduinoIoTCloud/pull/465) and [ArduinoBearSSL](https://github.com/arduino-libraries/ArduinoBearSSL) but it should word also with ESP32 WiFiClientSecure. Maybe a full connection log can give you more information about what is failing.

**Comment by djom202** [comment]
Hi @pennam,

I'm sharing with you the [logs](https://gist.github.com/djom202/e388ec8ced28f5c68b84dba615f19fa5), just remove the repetitive information over the connection status in order to reduce the size file. Also I've to test it without ArduinoCloud and it's works by hours with not issues.

**Comment by pennam** [comment]
@djom202 I see from the logs you are using a 3.x.x version of the ESP32 core. > 3.x.x have introduced a lot of changes and we did not have the chance to test them extensively with ArduinoIoTCloud.

Would you test the same sketch with core 2.0.17 ?

https://github.com/espressif/arduino-esp32/releases/tag/2.0.17

Thanks

**Comment by djom202** [comment]
Sure. Let me check it.

**Comment by djom202** [comment]
Hi @pennam,

Yeah you are right, I tested by hours with the version 2.0.17 works without issues. 

```
17:55:50.019 -> Wifi CONNECTED
17:55:50.019 -> RRSI: -85
17:55:50.051 -> AWS: CONNECTED
17:55:50.051 -> Successful subscription.
```

So, what I’m asking is if a newer version within the 2.X.X range could work for this case?

**Comment by pennam** [comment]
@djom202 goot news.

> So, what I’m asking is if a newer version within the 2.X.X range could work for this case?

sorry but i did not get your last question. A newer version of what?

**Comment by pennam** [comment]
2.0.17 should be the latests 2.x.x release of the esp core and is the one we have installed in our cloud builder.
