### ISSUE TITLE
Cannot connect to ArduinoIoTCloud

### ISSUE THREAD

**Issue by jmbeck** [arduino-libraries/ArduinoIoTCloud#77]
I get this every time I try to connect, any ideas?

```
[ 42816 ] Connected to [wifi]
[ 42817 ] Connecting to Arduino IoT Cloud...
[ 43124 ] Bogus NTP time from API, fallback to UDP method
[ 45229 ] Bogus NTP time from API, fallback to UDP method
[ 47206 ] Bogus NTP time from API, fallback to UDP method
```

**Comment by ubidefeo** [comment]
care to spare more details on the configuration?
Another user was having issues because his provider was blocking the NTP port.
We plan to integrate an option for http but haven't gotten around to it yet

**Comment by jmbeck** [comment]
Hi @ubidefeo.  I'm using Sonic.net internet via an eero router.  It also happens when I use my phone hotspot wifi on T-mobile in the US.

The eero is in a normal DHCP mode, no bridging or anything.

Do I need to set up port-forwarding for port 123?

I am just trying to control the onboard LED using the example.

**Comment by ubidefeo** [comment]
@jmbeck please provide more details such as
- arduino board (at this moment IoT Cloud only works on MKR1000, MKR WiFi 1010, MKR GSM 1400, Nano 33 IoT)
- if you have one of the above, have you been through the Arduino IoT Cloud Getting Started? (https://create.arduino.cc/getting-started)

**Comment by jmbeck** [comment]
@ubidefeo

* MKR WiFi 1010
* Yes, I have gone through the getting started steps.  Step 6 does not work.  I tried clicking the LED and it doesn't toggle.  Also tried opening the debug console and sending 'ON' and 'OFF'.  I get this:
```
list
{ "Ports": [], "Network": true }
{ "Ports": [ { "Name": "/dev/cu.usbmodem141401", "SerialNumber": "C18A4B1A50504332312E314AFF041307", "DeviceClass": "", "IsOpen": false, "IsPrimary": false, "Baud": 0, "BufferAlgorithm": "", "Ver": "1.1.90", "NetworkPort": false, "VendorID": "0x2341", "ProductID": "0x8054" } ], "Network": false }
OFF
{"Error" : "Could not understand command."}
```

The text area is disabled, so I couldn't send from the Step 6 page itself.

**Comment by jmbeck** [comment]
@ubidefeo

I got it to work just now!  It could be that I had gone through the setup twice, so I had two boards defined (but they were the same physical board).

My thing was probably configured with the wrong board.

I went through it a third time just now.  Deleted the original two boards on arduino cloud.  Then configured my 3rd board instance, and it now works.  Serial monitor shows this:

```
[ 21289 ] Connected to "[wifi]"
[ 21290 ] Connecting to Arduino IoT Cloud...
[ 21799 ] Bogus NTP time from API, fallback to UDP method
[ 24993 ] ERROR - Please verify your THING ID
[ 25700 ] Bogus NTP time from API, fallback to UDP method
[ 28677 ] ERROR - Please verify your THING ID
[ 29181 ] Bogus NTP time from API, fallback to UDP method
[ 32154 ] ERROR - Please verify your THING ID
[ 35430 ] ERROR - Please verify your THING ID
[ 38907 ] Connected to Arduino IoT Cloud
LED set to 0
LED set to 1
LED set to 0
LED set to 1
LED set to 0
LED set to 1
LED set to 0
LED set to 1
LED set to 0
```

**Comment by ubidefeo** [comment]
Nice to read you got it sorted.
trust me, I've been on this project for about a year and I still make these mistakes :)

I find these strange, though
```
[ 32154 ] ERROR - Please verify your THING ID
[ 35430 ] ERROR - Please verify your THING ID
```
they should not come up

**Comment by jmbeck** [comment]
I just tried it again and I didn't get these messages.

I had an older flash that had the wrong thing ID in it.  But this should have been overwritten before the WIFI connection was successful, I would think.

**Comment by ubidefeo** [comment]
gotcha
thank you for reporting, though
sometimes thanks to these issues we find hidden bugs :)
